### ISSUE TITLE
ParallaxHeaderMode(bottom) Layout Issue

### ISSUE THREAD

**Issue by DevChAe** [ngochiencse/HPParallaxHeader#1]
Hi,

Thanks for changing MXParallaxHeader to Swift.

I found a problem with ParallaxHeaderMode (bottom).

* HPParallaxHeader
<img width="613" alt="스크린샷 2021-07-02 오후 1 59 48" src="https://user-images.githubusercontent.com/45442864/124223021-dc461300-db3d-11eb-9a40-c5cad104f887.png">

* MXParallaxHeader
<img width="700" alt="스크린샷 2021-07-02 오후 2 00 07" src="https://user-images.githubusercontent.com/45442864/124223062-f3850080-db3d-11eb-8eec-0df99b52418d.png">

HPParallaxHeader is a topAnchor, but MXParallaxHeader is a bottomAnchor.

I hope this will be a quick fix.

**Comment by ngochiencse** [comment]
Thank you for your notice. I have fixed this problem. You can check in commits.
