### ISSUE TITLE
[Request]Migration Documents from MXParallaxHeader

### ISSUE THREAD

**Issue by sugitatestblue** [ngochiencse/HPParallaxHeader#3]
I think there are many `MXParallaxHeader` users.
I hope migration from Objective-C to Swift version.

**Comment by ngochiencse** [comment]
Currently Cocoadocs has been no longer working. Do you have any alternative suggestion?

**Comment by sugitatestblue** [comment]
unfortunately I have no idea.

It may write any alternative.
https://blog.cocoapods.org/CocoaPods-Metadata-Service/

**Comment by ngochiencse** [comment]
Hi I have update documentation link, you can check in README or here: https://ngochiencse.github.io/HPParallaxHeader/documentation/hpparallaxheader/ @sugitatestblue
