### ISSUE TITLE
HPScrollViewController viewDidLoad override

### ISSUE THREAD

**Issue by sugitatestblue** [ngochiencse/HPParallaxHeader#4]
HPScrollViewController's `viewDidLoad()` can't override in inherited class

**Comment by ngochiencse** [comment]
Ok let me see

**Comment by sugitatestblue** [comment]
Thank you for fix.

**Comment by sugitatestblue** [comment]
When will you release new edition?
Check and close

**Comment by ngochiencse** [comment]
I'm releasing but currently have some trouble with configuring cocoapods so it may takes a few day.

**Comment by ngochiencse** [comment]
Done, Please check version 1.1.8
